apiVersion: v1
kind: ResourceQuota
metadata:
  name: renvor-docs
  labels:
    app.kubernetes.io/name: renvor-docs
    app.kubernetes.io/part-of: renvor
    app.kubernetes.io/managed-by: flux
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 256Mi
    requests.ephemeral-storage: 768Mi
    limits.cpu: '2'
    limits.memory: 1Gi
    limits.ephemeral-storage: 2Gi
    pods: '6'
    persistentvolumeclaims: '0'
    services.loadbalancers: '0'
    services.nodeports: '0'
