apiVersion: v1
kind: ServiceAccount
metadata:
  name: renvor-docs
  labels:
    app.kubernetes.io/name: renvor-docs
    app.kubernetes.io/part-of: renvor
    app.kubernetes.io/managed-by: flux
automountServiceAccountToken: false
