apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: renvor-docs-staging

resources:
  - ../../base

images:
  - name: ghcr.io/renvor-rs/renvor-docs
    digest: sha256:8dee47665ac5b27cb77131db1bac3a6067a7616a6e590aac0e4f43741262872f

patches:
  - target:
      kind: Deployment
      name: renvor-docs
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/instance: renvor-docs-staging
      renvor.dev/environment: staging
