apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: renvor-docs-staging

resources:
  - ../../base

images:
  - name: ghcr.io/renvor-rs/renvor-docs
    digest: sha256:9240f8621a7bbfe735cb895298cc9fe6a75572e2e011a68d4405e11ee69ebfcd

patches:
  - target:
      kind: Deployment
      name: renvor-docs
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/instance: renvor-docs-staging
      renvor.dev/environment: staging
